archival_site = "test2"
archival_version = "0.7.0"
site_url = "https://hello.onarchival.dev"
prebuild = ["npm run ci", "npm run build"]

[editor_types.butt]
type = "video"

[editor_types.butt2]
type = "string"
validate = ["magic"]

[editor_types.metabutt]
type = "meta"
[[editor_types.metabutt.validate]]
path = "foo.bar.baz"
validate = "^[bB]"

[editor_types.custom_type]
type = "meta"
editor_url = "http://localhost:9090/editor.html"
