# This file is used to define the objects available on your site.

[section]
name = "string"
body = "markdown"
video_aliased = "butt"
file = "upload"

[section.child]
string_validated = "butt2"
stuff = "metabutt"
