order = -1
body = """
Here is some *content*
"""
name = "Some Content"

[video]
filename = "IMG_0833.MOV"
sha = "87fa344c44c086b9d991e5cc73afba33c7abbadd22c8e579644d29fd73399663"
mime = "video/quicktime"
name = "IMG_0833.MOV"
display_type = "video"
