name: Archival
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Archival Build
        uses: jesseditson/archival@action-artifacts
